// Copyright (c) 2025 Archmagece
// SPDX-License-Identifier: MIT

package templates

import (
	"strings"
	"testing"
)

func TestGetRaw(t *testing.T) {
	tests := []struct {
		name     TemplateName
		contains string
	}{
		{RepositoriesBasic, "kind: repositories"},
		{RepositoriesChild, "parent:"},
		{RepositoriesBootstrap, "Generated by gz-git"},
		{WorkspaceWorkstation, "kind: workspace"},
		{WorkspaceForge, "source:"},
		{Profile, "provider:"},
	}

	for _, tt := range tests {
		t.Run(string(tt.name), func(t *testing.T) {
			content, err := GetRaw(tt.name)
			if err != nil {
				t.Fatalf("GetRaw(%s) error: %v", tt.name, err)
			}
			if !strings.Contains(string(content), tt.contains) {
				t.Errorf("GetRaw(%s) missing expected content %q", tt.name, tt.contains)
			}
		})
	}
}

func TestRender_RepositoriesBasic(t *testing.T) {
	data := RepositoriesBasicData{
		Name:        "test-devbox",
		Team:        "backend",
		Description: "Test devbox",
		Strategy:    "pull",
		Parallel:    10,
		Repositories: []RepoData{
			{Name: "repo-a", URL: "git@github.com:org/repo-a.git", Path: "./repo-a"},
			{Name: "repo-b", URL: "git@github.com:org/repo-b.git", Path: "./repo-b", Branch: "develop"},
		},
	}

	result, err := Render(RepositoriesBasic, data)
	if err != nil {
		t.Fatalf("Render error: %v", err)
	}

	expected := []string{
		"version: 1",
		"kind: repositories",
		"name: test-devbox",
		"strategy: pull",
		"parallel: 10",
		"name: repo-a",
		"name: repo-b",
		"branch: develop",
	}

	for _, exp := range expected {
		if !strings.Contains(result, exp) {
			t.Errorf("Render result missing %q\nGot:\n%s", exp, result)
		}
	}
}

func TestRender_Bootstrap(t *testing.T) {
	data := BootstrapData{
		Parent:  "/path/to/parent/.gz-git.yaml",
		Profile: "work",
	}

	result, err := Render(RepositoriesBootstrap, data)
	if err != nil {
		t.Fatalf("Render error: %v", err)
	}

	expected := []string{
		"version: 1",
		"kind: repositories",
		"parent: /path/to/parent/.gz-git.yaml",
		"profile: work",
	}

	for _, exp := range expected {
		if !strings.Contains(result, exp) {
			t.Errorf("Render result missing %q\nGot:\n%s", exp, result)
		}
	}
}

func TestRender_BootstrapNoProfile(t *testing.T) {
	data := BootstrapData{
		Parent: "/path/to/parent/.gz-git.yaml",
	}

	result, err := Render(RepositoriesBootstrap, data)
	if err != nil {
		t.Fatalf("Render error: %v", err)
	}

	if strings.Contains(result, "profile:") {
		t.Errorf("Render result should not contain profile when empty\nGot:\n%s", result)
	}
}

func TestList(t *testing.T) {
	templates := List()
	if len(templates) == 0 {
		t.Error("List() returned empty")
	}

	// Verify all listed templates exist
	for _, name := range templates {
		_, err := GetRaw(name)
		if err != nil {
			t.Errorf("Listed template %s not found: %v", name, err)
		}
	}
}

func TestGetRaw_NotFound(t *testing.T) {
	_, err := GetRaw("nonexistent.yaml")
	if err == nil {
		t.Error("GetRaw should fail for nonexistent template")
	}
}
