// Copyright (c) 2025 Archmagece
// SPDX-License-Identifier: MIT

// Package templates provides embedded YAML templates for configuration generation.
// Templates are compiled into the binary using Go's embed package.
package templates

import (
	"bytes"
	"embed"
	"fmt"
	"text/template"
)

//go:embed *.yaml
var fs embed.FS

// TemplateName identifies available templates.
type TemplateName string

const (
	// RepositoriesBasic is a basic repositories config with flat repo list.
	RepositoriesBasic TemplateName = "repositories-basic.yaml"

	// RepositoriesChild is a child config that inherits from parent.
	RepositoriesChild TemplateName = "repositories-child.yaml"

	// RepositoriesBootstrap is a minimal bootstrap config for auto-generation.
	RepositoriesBootstrap TemplateName = "repositories-bootstrap.yaml"

	// RepositoriesSample is a sample config with comments for new users.
	RepositoriesSample TemplateName = "repositories-sample.yaml"

	// RepositoriesScanned is for configs generated by workspace scan.
	RepositoriesScanned TemplateName = "repositories-scanned.yaml"

	// RepositoriesForge is for configs generated from forge API.
	RepositoriesForge TemplateName = "repositories-forge.yaml"

	// RepositoriesChildForge is for child configs with forge-synced repositories.
	RepositoriesChildForge TemplateName = "repositories-child-forge.yaml"

	// WorkspacesChildForge is for child configs with workspaces map format.
	WorkspacesChildForge TemplateName = "workspaces-child-forge.yaml"

	// WorkspaceWorkstation is a top-level workstation config with profiles.
	WorkspaceWorkstation TemplateName = "workspace-workstation.yaml"

	// WorkspaceForge is a workspace config with forge source integration.
	WorkspaceForge TemplateName = "workspace-forge.yaml"

	// Profile is a standalone profile configuration.
	Profile TemplateName = "profile.yaml"
)

// GetRaw returns the raw template content without processing.
func GetRaw(name TemplateName) ([]byte, error) {
	return fs.ReadFile(string(name))
}

// Render renders a template with the given data.
// Returns an error if the template cannot be found, parsed, or executed.
// For cases where template errors indicate programmer error, use [MustRender] instead.
func Render(name TemplateName, data any) (string, error) {
	content, err := fs.ReadFile(string(name))
	if err != nil {
		return "", fmt.Errorf("read template %s: %w", name, err)
	}

	tmpl, err := template.New(string(name)).Parse(string(content))
	if err != nil {
		return "", fmt.Errorf("parse template %s: %w", name, err)
	}

	var buf bytes.Buffer
	if err := tmpl.Execute(&buf, data); err != nil {
		return "", fmt.Errorf("execute template %s: %w", name, err)
	}

	return buf.String(), nil
}

// MustRender renders a template and panics on error.
//
// PANIC CONDITIONS:
//   - Template name not found (embedded file missing)
//   - Template syntax error (malformed template)
//   - Template execution error (missing field in data, type mismatch)
//
// WHEN TO USE:
//   - Initialization code where templates are known valid at compile time
//   - Tests and examples where failure indicates programmer error
//   - Embedded templates that ship with the binary (cannot be missing)
//
// WHEN NOT TO USE:
//   - User-provided templates (use [Render] instead)
//   - Templates loaded from external files
//   - Anywhere template errors should be recoverable
//
// For recoverable error handling, use [Render] which returns an error.
func MustRender(name TemplateName, data any) string {
	result, err := Render(name, data)
	if err != nil {
		panic(err)
	}
	return result
}

// List returns all available template names.
func List() []TemplateName {
	return []TemplateName{
		RepositoriesBasic,
		RepositoriesChild,
		RepositoriesBootstrap,
		RepositoriesSample,
		RepositoriesScanned,
		RepositoriesForge,
		RepositoriesChildForge,
		WorkspacesChildForge,
		WorkspaceWorkstation,
		WorkspaceForge,
		Profile,
	}
}

// ================================================================================
// Template Data Structures
// ================================================================================

// RepositoriesBasicData is the data for RepositoriesBasic template.
type RepositoriesBasicData struct {
	Name         string
	Team         string
	Description  string
	Strategy     string // reset|pull|fetch
	Parallel     int
	Repositories []RepoData
}

// RepoData represents a single repository entry.
type RepoData struct {
	Name        string
	URL         string
	Path        string
	Branch      string
	Description string
}

// RepositoriesChildData is the data for RepositoriesChild template.
type RepositoriesChildData struct {
	Parent       string
	Profile      string
	Repositories []RepoData
}

// BootstrapData is the data for RepositoriesBootstrap template.
type BootstrapData struct {
	Parent  string
	Profile string
}

// ChildForgeData is the data for RepositoriesChildForge template.
// Used when generating child configs from forge-synced workspaces.
type ChildForgeData struct {
	Parent       string
	Profile      string
	GeneratedAt  string // RFC3339 timestamp
	Provider     string // github, gitlab, gitea
	Organization string
	Strategy     string
	Parallel     int
	CloneProto   string
	SSHPort      int
	Repositories []ChildForgeRepoData
}

// ChildForgeRepoData represents a repository entry in child forge config.
type ChildForgeRepoData struct {
	Name   string
	URL    string
	Path   string // relative path from workspace root
	Branch string
}

// ChildWorkspacesData is the data for WorkspacesChildForge template.
// Used when generating child configs with workspaces map format.
type ChildWorkspacesData struct {
	Parent       string
	Profile      string
	GeneratedAt  string // RFC3339 timestamp
	Provider     string // github, gitlab, gitea
	Organization string
	Workspaces   []ChildWorkspaceEntry
}

// ChildWorkspaceEntry represents a workspace entry in workspaces map format.
type ChildWorkspaceEntry struct {
	Name string
	Path string
}

// WorkstationData is the data for WorkspaceWorkstation template.
type WorkstationData struct {
	Name       string
	Owner      string
	Parallel   int
	CloneProto string
	Profiles   map[string]ProfileData
	Workspaces map[string]WorkspaceData
}

// ProfileData represents a profile entry.
type ProfileData struct {
	Provider         string
	BaseURL          string
	Token            string
	CloneProto       string
	SSHPort          int
	Parallel         int
	IncludeSubgroups bool
	SubgroupMode     string
	Sync             *SyncData
}

// SyncData represents sync settings.
type SyncData struct {
	Strategy   string
	MaxRetries int
}

// WorkspaceData represents a workspace entry.
type WorkspaceData struct {
	Path     string
	Type     string // forge|git|config
	Profile  string
	Source   *ForgeSourceData
	Sync     *SyncData
	Parallel int
}

// ForgeSourceData represents a forge source.
type ForgeSourceData struct {
	Provider         string
	Org              string
	BaseURL          string
	Token            string
	IncludeSubgroups bool
	SubgroupMode     string
}

// WorkspaceForgeData is the data for WorkspaceForge template.
type WorkspaceForgeData struct {
	Parent     string
	Profile    string
	Name       string
	Team       string
	Workspaces map[string]WorkspaceData
}

// ScannedData is the data for RepositoriesScanned template.
type ScannedData struct {
	ScannedAt    string // RFC3339 timestamp
	BasePath     string // Base path for relative paths (default: ".")
	Count        int    // Number of repos found
	Strategy     string
	Parallel     int
	MaxRetries   int
	CloneProto   string
	SSHPort      int
	Repositories []ScannedRepoData
}

// ScannedRepoData represents a scanned repository entry.
type ScannedRepoData struct {
	Name              string
	Path              string
	URL               string            // Primary URL (typically origin)
	AdditionalRemotes map[string]string // Additional remotes (name -> URL)
}

// ForgeGeneratedData is the data for RepositoriesForge template.
type ForgeGeneratedData struct {
	GeneratedAt  string // RFC3339 timestamp
	Provider     string // github, gitlab, gitea
	Organization string
	Strategy     string
	Parallel     int
	MaxRetries   int
	CloneProto   string
	SSHPort      int
	Repositories []ForgeRepoData
}

// ForgeRepoData represents a forge repository entry.
type ForgeRepoData struct {
	Name string
	URL  string
	Path string
}
