// Copyright (c) 2025 Gizzahub
// SPDX-License-Identifier: MIT

package workspacecli

import (
	"bytes"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"reflect"
	"sort"
	"strings"
	"testing"
)

// TestWorkspaceDryRunReadOnly pins the read-only contract of `workspace sync
// --dry-run`: a preview must not modify the workspace tree. Child directories,
// regular user config files, and existing symlinks have to survive both the
// default and the `--format json` dry-run byte-for-byte, while a normal run of
// the same workspaces keeps replacing configLink targets and bootstrapping
// missing child configs exactly as before.
func TestWorkspaceDryRunReadOnly(t *testing.T) {
	t.Run("dry-run default format leaves the tree untouched", func(t *testing.T) {
		root := newDryRunChildConfigTree(t)
		before := snapshotDryRunTree(t, root)

		runWorkspaceSyncCommand(t, root, "-c", filepath.Join(root, DefaultConfigFile), "--dry-run")

		assertDryRunTreeIntact(t, root)

		after := snapshotDryRunTree(t, root)
		assertDryRunSnapshotsEqual(t, before, after)
	})

	t.Run("dry-run json format leaves the tree untouched", func(t *testing.T) {
		root := newDryRunChildConfigTree(t)
		before := snapshotDryRunTree(t, root)

		runWorkspaceSyncCommand(t, root, "-c", filepath.Join(root, DefaultConfigFile), "--dry-run", "--format", "json")

		assertDryRunTreeIntact(t, root)

		after := snapshotDryRunTree(t, root)
		assertDryRunSnapshotsEqual(t, before, after)
	})

	t.Run("normal run still links and bootstraps child configs", func(t *testing.T) {
		root := newDryRunChildConfigTree(t)

		// normal.yaml holds the configLink/bootstrap workspaces without the git
		// workspaces, so the run finishes cleanly without cloning anything.
		runWorkspaceSyncCommand(t, root, "-c", filepath.Join(root, "normal.yaml"))

		linkedTarget := filepath.Join(root, "links", "linked.yaml")

		// The hand-maintained regular config is replaced by the configLink
		// symlink (warn & replace contract).
		assertSymlinkConfig(t, filepath.Join(root, "ws-linked", DefaultConfigFile), linkedTarget)

		// The pre-existing symlink is re-pointed at the configured source.
		assertSymlinkConfig(t, filepath.Join(root, "ws-symlink", DefaultConfigFile), linkedTarget)

		// The missing child workspace directory is bootstrapped with a
		// generated config.
		bootstrapped := filepath.Join(root, "ws-missing", DefaultConfigFile)
		content, err := os.ReadFile(bootstrapped)
		if err != nil {
			t.Fatalf("bootstrap config not created: %v", err)
		}
		if !strings.Contains(string(content), "Generated by gz-git") {
			t.Errorf("bootstrap config lacks generated marker, got:\n%s", content)
		}
	})
}

// dryRunChildConfigUserFile is the hand-maintained config content that must
// survive a dry-run verbatim and is replaced by a symlink on a normal run.
const dryRunChildConfigUserFile = "# hand-maintained workspace config\nrepositories: []\n"

// dryRunChildConfigGitFile is the same scenario for a type=git workspace,
// whose config would be replaced by planGitWorkspaces.
const dryRunChildConfigGitFile = "# hand-maintained git workspace config\nrepositories: []\n"

// newDryRunChildConfigTree builds a workspace fixture covering every child
// config state the dry-run must not touch:
//   - ws-linked:    regular user file + configLink (ensureChildConfigs replace)
//   - ws-symlink:   existing symlink aimed elsewhere + configLink (re-point)
//   - ws-missing:   absent directory (bootstrap MkdirAll + WriteFile)
//   - ws-git:       regular user file + configLink on a git workspace
//   - deep/nested:  absent parent of a hooked git workspace (hook MkdirAll)
func newDryRunChildConfigTree(t *testing.T) string {
	t.Helper()
	root := t.TempDir()

	linksDir := filepath.Join(root, "links")
	dryRunMkdir(t, linksDir)
	linkedSrc := filepath.Join(linksDir, "linked.yaml")
	otherSrc := filepath.Join(linksDir, "other.yaml")
	dryRunWriteFile(t, linkedSrc, "repositories: []\n# linked source config\n")
	dryRunWriteFile(t, otherSrc, "repositories: []\n# other source config\n")

	wsLinked := filepath.Join(root, "ws-linked")
	dryRunMkdir(t, wsLinked)
	dryRunWriteFile(t, filepath.Join(wsLinked, DefaultConfigFile), dryRunChildConfigUserFile)

	wsSymlink := filepath.Join(root, "ws-symlink")
	dryRunMkdir(t, wsSymlink)
	if err := os.Symlink(otherSrc, filepath.Join(wsSymlink, DefaultConfigFile)); err != nil {
		t.Fatal(err)
	}

	wsGit := filepath.Join(root, "ws-git")
	dryRunMkdir(t, wsGit)
	dryRunWriteFile(t, filepath.Join(wsGit, DefaultConfigFile), dryRunChildConfigGitFile)

	// ws-missing and deep/nested are deliberately absent.

	// The git origins never exist: planning never contacts them and dry-run
	// never executes, so a bug that leaks execution fails fast offline.
	deadOrigin := filepath.Join(root, "no-such-origin.git")

	dryRunConfig := "workspaces:\n" +
		"  linked-user-file:\n" +
		"    path: ws-linked\n" +
		"    configLink: ./links/linked.yaml\n" +
		"  linked-symlink:\n" +
		"    path: ws-symlink\n" +
		"    configLink: ./links/linked.yaml\n" +
		"  missing-bootstrap:\n" +
		"    path: ws-missing\n" +
		"  git-linked:\n" +
		"    type: git\n" +
		"    url: " + deadOrigin + "\n" +
		"    path: ws-git\n" +
		"    configLink: ./links/linked.yaml\n" +
		"  git-hooked:\n" +
		"    type: git\n" +
		"    url: " + deadOrigin + "\n" +
		"    path: deep/nested/hooked\n" +
		"    hooks:\n" +
		"      before:\n" +
		"        - touch hook-marker.txt\n"
	dryRunWriteFile(t, filepath.Join(root, DefaultConfigFile), dryRunConfig)

	normalConfig := "workspaces:\n" +
		"  linked-user-file:\n" +
		"    path: ws-linked\n" +
		"    configLink: ./links/linked.yaml\n" +
		"  linked-symlink:\n" +
		"    path: ws-symlink\n" +
		"    configLink: ./links/linked.yaml\n" +
		"  missing-bootstrap:\n" +
		"    path: ws-missing\n"
	dryRunWriteFile(t, filepath.Join(root, "normal.yaml"), normalConfig)

	return root
}

// runWorkspaceSyncCommand executes the sync command from dir and fails the
// test unless it exits cleanly.
func runWorkspaceSyncCommand(t *testing.T, dir string, args ...string) {
	t.Helper()
	t.Chdir(dir)

	var output bytes.Buffer
	cmd := CommandFactory{}.newSyncCmd()
	cmd.SetOut(&output)
	cmd.SetErr(&output)
	cmd.SetArgs(args)
	if err := cmd.Execute(); err != nil {
		t.Fatalf("workspace sync %s failed: %v\n%s", strings.Join(args, " "), err, output.String())
	}
}

// dryRunTreeEntry is one node of a workspace tree fingerprint: kind, mode,
// and payload (file content or symlink target).
type dryRunTreeEntry struct {
	relPath string
	kind    string
	mode    string
	payload string
}

// snapshotDryRunTree records every entry under root so a dry-run can be
// proven read-only by comparing before/after fingerprints.
func snapshotDryRunTree(t *testing.T, root string) []dryRunTreeEntry {
	t.Helper()
	var entries []dryRunTreeEntry
	err := filepath.WalkDir(root, func(path string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		if path == root {
			return nil
		}
		rel, relErr := filepath.Rel(root, path)
		if relErr != nil {
			return relErr
		}
		info, infoErr := d.Info()
		if infoErr != nil {
			return infoErr
		}
		entry := dryRunTreeEntry{relPath: rel, mode: info.Mode().String()}
		switch {
		case info.Mode()&os.ModeSymlink != 0:
			target, readErr := os.Readlink(path)
			if readErr != nil {
				return readErr
			}
			entry.kind = "symlink"
			entry.payload = target
		case info.IsDir():
			entry.kind = "dir"
		default:
			content, readErr := os.ReadFile(path) // #nosec G304 -- fixture path under the test temp root.
			if readErr != nil {
				return readErr
			}
			entry.kind = "file"
			entry.payload = string(content)
		}
		entries = append(entries, entry)
		return nil
	})
	if err != nil {
		t.Fatalf("snapshot %s: %v", root, err)
	}
	sort.Slice(entries, func(i, j int) bool { return entries[i].relPath < entries[j].relPath })
	return entries
}

func assertDryRunSnapshotsEqual(t *testing.T, before, after []dryRunTreeEntry) {
	t.Helper()
	if reflect.DeepEqual(before, after) {
		return
	}
	t.Fatalf("dry-run modified the workspace tree\nbefore:\n%s\nafter:\n%s",
		formatDryRunSnapshot(before), formatDryRunSnapshot(after))
}

func formatDryRunSnapshot(entries []dryRunTreeEntry) string {
	var b strings.Builder
	for _, e := range entries {
		fmt.Fprintf(&b, "  %-12s %-12s %s %q\n", e.kind, e.mode, e.relPath, e.payload)
	}
	return b.String()
}

// assertDryRunTreeIntact re-checks the named child-config states with precise
// failure messages, on top of the generic snapshot comparison.
func assertDryRunTreeIntact(t *testing.T, root string) {
	t.Helper()

	linked := filepath.Join(root, "ws-linked", DefaultConfigFile)
	assertRegularConfig(t, linked, dryRunChildConfigUserFile)

	gitCfg := filepath.Join(root, "ws-git", DefaultConfigFile)
	assertRegularConfig(t, gitCfg, dryRunChildConfigGitFile)

	symlinkCfg := filepath.Join(root, "ws-symlink", DefaultConfigFile)
	fi, err := os.Lstat(symlinkCfg)
	if err != nil {
		t.Fatalf("existing symlink config missing after dry-run: %v", err)
	}
	if fi.Mode()&os.ModeSymlink == 0 {
		t.Fatalf("existing symlink config %s became %v", symlinkCfg, fi.Mode())
	}
	target, err := os.Readlink(symlinkCfg)
	if err != nil {
		t.Fatal(err)
	}
	if want := filepath.Join(root, "links", "other.yaml"); target != want {
		t.Errorf("symlink target = %s, want unchanged %s", target, want)
	}

	for _, absent := range []string{
		filepath.Join(root, "ws-missing"),
		filepath.Join(root, "deep"),
	} {
		if _, err := os.Lstat(absent); !os.IsNotExist(err) {
			t.Errorf("dry-run created %s", absent)
		}
	}
}

func assertRegularConfig(t *testing.T, path, wantContent string) {
	t.Helper()
	fi, err := os.Lstat(path)
	if err != nil {
		t.Fatalf("config %s missing: %v", path, err)
	}
	if fi.Mode()&os.ModeSymlink != 0 {
		t.Fatalf("config %s was replaced by a symlink (mode %v)", path, fi.Mode())
	}
	got, err := os.ReadFile(path) // #nosec G304 -- fixture path under the test temp root.
	if err != nil {
		t.Fatal(err)
	}
	if string(got) != wantContent {
		t.Errorf("config %s content = %q, want %q", path, got, wantContent)
	}
}

func assertSymlinkConfig(t *testing.T, path, wantTarget string) {
	t.Helper()
	fi, err := os.Lstat(path)
	if err != nil {
		t.Fatalf("config %s missing: %v", path, err)
	}
	if fi.Mode()&os.ModeSymlink == 0 {
		t.Fatalf("config %s is a regular file (%v), want symlink", path, fi.Mode())
	}
	got, err := os.Readlink(path)
	if err != nil {
		t.Fatal(err)
	}
	if got != wantTarget {
		t.Errorf("symlink %s target = %s, want %s", path, got, wantTarget)
	}
}

func dryRunMkdir(t *testing.T, dir string) {
	t.Helper()
	if err := os.MkdirAll(dir, 0o755); err != nil {
		t.Fatal(err)
	}
}

func dryRunWriteFile(t *testing.T, path, content string) {
	t.Helper()
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}
