// Copyright (c) 2026 Gizzahub
// SPDX-License-Identifier: MIT

package cmd

import (
	"bytes"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/spf13/cobra"
	"github.com/spf13/pflag"
)

func runGenDocs(t *testing.T, args ...string) error {
	t.Helper()
	root := fullCommandTree()
	var out bytes.Buffer
	root.SetOut(&out)
	root.SetErr(&out)
	root.SetArgs(append([]string{"gen-docs"}, args...))
	resetGenDocsFlags(root)
	t.Cleanup(func() {
		root.SetOut(nil)
		root.SetErr(nil)
		root.SetArgs(nil)
		resetGenDocsFlags(root)
	})
	return executeCommand(root)
}

// resetGenDocsFlags clears values Cobra keeps between Execute calls, so
// each run sees only its own arguments.
func resetGenDocsFlags(root *cobra.Command) {
	for _, c := range root.Commands() {
		if c.Name() != "gen-docs" {
			continue
		}
		c.Flags().VisitAll(func(f *pflag.Flag) {
			_ = f.Value.Set(f.DefValue)
			f.Changed = false
		})
	}
}

func TestGenDocsRejectsBadSourceDateEpoch(t *testing.T) {
	t.Setenv("SOURCE_DATE_EPOCH", "yesterday")
	err := runGenDocs(t, "--man-dir", t.TempDir())
	if err == nil || !strings.Contains(err.Error(), "SOURCE_DATE_EPOCH") {
		t.Fatalf("err = %v, want a SOURCE_DATE_EPOCH error", err)
	}
}

// treeShape records what the generators must leave untouched: the command
// set (Cobra adds help children while rendering) and each auto-gen flag.
func treeShape(root *cobra.Command) string {
	var b strings.Builder
	walkAll(root, func(c *cobra.Command) {
		b.WriteString(c.CommandPath())
		if c.DisableAutoGenTag {
			b.WriteString(" noGenTag")
		}
		for _, child := range c.Commands() {
			if child.Name() == "help" {
				b.WriteString(" +help")
			}
		}
		b.WriteString("\n")
	})
	return b.String()
}

func TestGenDocsWritesManAndMarkdownTrees(t *testing.T) {
	t.Setenv("SOURCE_DATE_EPOCH", "1767225600") // 2026-01-01
	manDir := filepath.Join(t.TempDir(), "man")
	mdDir := filepath.Join(t.TempDir(), "md")
	shape := treeShape(fullCommandTree())
	long := integrateBootstrapApplyCmd.Long

	if err := runGenDocs(t, "--man-dir", manDir, "--markdown-dir", mdDir); err != nil {
		t.Fatalf("gen-docs: %v", err)
	}

	man, err := os.ReadFile(filepath.Join(manDir, "gz-git-integrate-bootstrap-apply.1"))
	if err != nil {
		t.Fatalf("read man page: %v", err)
	}
	if !strings.Contains(string(man), "readiness-contract") {
		t.Errorf("man page missing effect:\n%s", man)
	}
	if !strings.Contains(string(man), `.TH "GZ-GIT-INTEGRATE-BOOTSTRAP-APPLY" "1" "Jan 2026"`) {
		t.Errorf("man header not titled per command with the pinned date:\n%s", strings.SplitN(string(man), "\n", 3)[1])
	}
	md, err := os.ReadFile(filepath.Join(mdDir, "gz-git_integrate_bootstrap_plan.md"))
	if err != nil {
		t.Fatalf("read markdown page: %v", err)
	}
	if !strings.Contains(string(md), "Effect: mutating (tracking-refs)") {
		t.Errorf("markdown page missing effect:\n%s", md)
	}
	if strings.Contains(string(md), "Auto generated by spf13/cobra") {
		t.Errorf("markdown carries a date-stamped autogen tag; installs would not be reproducible")
	}

	if integrateBootstrapApplyCmd.Long != long {
		t.Errorf("Long was not restored after rendering: %q", integrateBootstrapApplyCmd.Long)
	}
	if got := treeShape(fullCommandTree()); got != shape {
		t.Errorf("rendering left the shared command tree changed")
	}

	// Same commit, same pages.
	again := filepath.Join(t.TempDir(), "man")
	if err := runGenDocs(t, "--man-dir", again); err != nil {
		t.Fatalf("gen-docs again: %v", err)
	}
	second, err := os.ReadFile(filepath.Join(again, "gz-git-integrate-bootstrap-apply.1"))
	if err != nil {
		t.Fatalf("read second man page: %v", err)
	}
	if !bytes.Equal(man, second) {
		t.Errorf("man pages differ between two renders")
	}
}

func TestGenDocsRequiresADirectory(t *testing.T) {
	if err := runGenDocs(t); err == nil || !strings.Contains(err.Error(), "--man-dir") {
		t.Fatalf("err = %v, want a missing-directory error", err)
	}
}

func TestHelpDoesNotListGenDocs(t *testing.T) {
	out, err := runRootHelp(t, "--all")
	if err != nil {
		t.Fatalf("help --all: %v", err)
	}
	if strings.Contains(out, "gen-docs") {
		t.Errorf("help --all lists the hidden gen-docs command")
	}
}
